title: Default Page
image:
  back: "blue-200"
  icon:

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          description:
            type: writer
            label: Description

          link_text:
            type: text
            label: Link text
            width: 1/2

          link:
            type: url
            label: Link
            width: 1/2

  sidebar:
    width: 1/3
    sections:
      images:
        label: Images
        type: files
        layout: cards
        # template: image
        # info: "{{ file.dimensions }}"
        image:
          ratio: 5/4
          cover: true
        size: small
