title: Default Page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          description:
            type: writer
            label: Description
  sidebar:
    width: 1/3
    sections:
      images:
        label: Images
        type: files
        layout: cards
        # template: image
        # info: "{{ file.dimensions }}"
        image:
          ratio: 5/4
          cover: true
        size: small
