title: 🪩

tabs:
  pages:
    label: Pages
    sections:
      listedPages:
        type: pages
        headline: listed
        status: listed
        create: default
        image: icon

      unlistedPages:
        type: pages
        headline: unlisted
        status: unlisted
        create: default
        image: icon

  settings:
    label: Settings
    sections:
      appearance:
        type: fields
        fields:
          title:
            label: Site Title
            type: text
            icon: title

          titleDisplay:
            label: Display Title
            type: text
            icon: title
            width: 1/2

          subtitle:
            label: Subtitle
            type: text
            icon: title
            width: 1/2

          email:
            label: Contact Email
            type: email

          socials:
            label: Socials
            type: structure
            fields:
              name:
                label: Name
                type: text
              email:
                label: Email
                type: email
              link:
                label: Link
                type: url

          acknowledgement:
            label: Acknowledgement of Country
            type: writer

          seo:
            type: headline
            label: SEO

          metaDescription:
            label: Meta Description
            type: writer

          metaKeywords:
            label: Meta Keywords
            type: writer

  media:
    label: files
    sections:
      ae_program:
        label: AE Program
        type: files
        template: ae_program

      ae_logo:
        label: AE logo
        type: files
        template: ae_logo
        multiple: false
        max: 1
        cover: true

      ae_swamp_svg:
        label: AE Swamp Icons
        type: files
        template: ae_swamp_svg
        layout: table
        columns:
          title: false
          prompt:
            label: Prompt Text
            type: text
          is_prompt:
            label: Use as Prompt?
            type: toggle
        help: SVG file of Swamp Icons for the homepage. Add prompt text to use icon in prompt rotation.

      ae_favicon:
        label: AE Favicon
        type: files
        template: ae_favicon
        multiple: false
        max: 1
        cover: true

      # ae_logo_menu:
      #   label: AE logos (menu version)
      #   type: files
      #   template: ae_logo_menu

      # ae_logo_combined:
      #   label: AE logos (combined version)
      #   type: files
      #   template: ae_logo_combined

      # audio_intro:
      #   type: files
      #   label: Audio Introduction
      #   template: audio_intro
      #   multiple: true
      #   help: Audio introduction to the festival.

      # audio_intro_text:
      #   type: fields
      #   fields:
      #     audio_intro_text:
      #       label: Audio Introduction Text
      #       type: writer
      #       help: Text to accompany the audio introduction.

      # audio_intro_transcription:
      #   type: fields
      #   fields:
      #     audio_intro_transcription:
      #       label: Audio Introduction Transcription
      #       type: writer
      #       help: Displayed in Plain Text View.

      ae_mix:
        label: AE Mix
        type: files
        template: audio_ae_mix
        multiple: false
        help: Audio mix for the festival.

      prompt_info:
        label: Prompt Info
        type: fields
        fields:
          prompt_info:
            label: Audio Upload Instructions
            type: writer

      # ae_prompts:
      #   label: AE Prompts
      #   type: files
      #   template: ae_prompts
      #   layout: table
      #   columns:
      #     title: false
      #     prompt_text:
      #       label: Prompt Text
      #       type: text
      #     prompt_icon:
      #       label: Icon
      #       type: files
      #       query: site.files.filterBy('template', 'ae_swamp_svg')
      #       multiple: false
      #   help: Select an icon for each prompt.
